# Generated by Django 4.1.6 on 2023-02-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name="teacher",
            name="subject",
            field=models.ManyToManyField(to="testdb.subject"),
        ),
    ]
